import { getWakeOnEventModes, getWoeFlags } from './formOptions';

export const PRIVATE_SETTINGS_LENGTH = 76;
export const PUBLIC_SETTINGS_LENGTH = 20;

export const PUBLIC_SETTINGS_DEFAULT_VALUE = '054114001e001e006801';

export const OP_CODES = {
  READ_ONLY_FILL_INTERNALS: 11,
  FILL_GW_CLIENT_FROM_DEVICE: 12,
  READ_DEVICE_VERSION: 13,
  LORA_REBOOT_ONLY: 64,
  LORA_REBOOT_AND_FORMAT: 65,
  SIGNATURE_REFERENCE_REQUESTED: 66,
  NWTIME_SYNC_AND_STATUS_UPDATE: 67,
  RX_PUB_SETTINGS_UPDATE: 70,
  RX_PRV_SETTINGS_UPDATE: 71,
  RX_PUB_SETTINGS_UPDATE_CLIENT_LOCK: 72,
  RX_PRV_SETTINGS_UPDATE_CLIENT_LOCK: 73,
  RX_FULL_SETTINGS_REQUESTED: 81,
  RX_SIG_SETTINGS_UPDATE: 74,
} as const;

export const SYNC_MODES = getWakeOnEventModes();
export const FLAGS = getWoeFlags();
